package top.jlen.vod.ui

import androidx.compose.runtime.Composable
import top.jlen.vod.data.FindPasswordEditor
import top.jlen.vod.data.MembershipPlan
import top.jlen.vod.data.RegisterEditor
import top.jlen.vod.data.UserProfileEditor

@Composable
fun AccountScreen(
    state: AccountUiState,
    onUserNameChange: (String) -> Unit,
    onPasswordChange: (String) -> Unit,
    onLogin: () -> Unit,
    onLogout: () -> Unit,
    onSelectSection: (AccountSection) -> Unit,
    onRefreshSection: () -> Unit,
    onChangePortrait: () -> Unit,
    onOpenHistoryRecord: (top.jlen.vod.data.UserCenterItem) -> Unit,
    onOpenFollow: () -> Unit,
    onLoadMoreHistory: () -> Unit,
    onDeleteHistory: (String) -> Unit,
    onClearHistory: () -> Unit,
    onUpgradeMembership: (MembershipPlan) -> Unit,
    onRedeemMembershipCard: (String, String) -> Unit,
    onSignInMembership: () -> Unit,
    onOpenPointLogs: () -> Unit,
    onProfileEditorChange: ((UserProfileEditor) -> UserProfileEditor) -> Unit,
    onProfileTabChange: (Boolean) -> Unit,
    onSaveProfile: () -> Unit,
    onAuthModeChange: (AccountAuthMode) -> Unit,
    onRegisterEditorChange: ((RegisterEditor) -> RegisterEditor) -> Unit,
    onRefreshRegisterCaptcha: () -> Unit,
    onSendRegisterCode: () -> Unit,
    onRegister: () -> Unit,
    onFindPasswordEditorChange: ((FindPasswordEditor) -> FindPasswordEditor) -> Unit,
    onSendFindPasswordCode: () -> Unit,
    onFindPassword: () -> Unit,
    onOpenSettingsUpdate: () -> Unit,
    onOpenSettingsCache: () -> Unit,
    onOpenSettingsAgreement: () -> Unit,
    onOpenSettingsLogs: () -> Unit,
    onSendEmailCode: () -> Unit,
    onBindEmail: () -> Unit,
    onUnbindEmail: () -> Unit,
) = LegacyAccountScreen(
    state = state,
    onUserNameChange = onUserNameChange,
    onPasswordChange = onPasswordChange,
    onLogin = onLogin,
    onLogout = onLogout,
    onSelectSection = onSelectSection,
    onRefreshSection = onRefreshSection,
    onChangePortrait = onChangePortrait,
    onOpenHistoryRecord = onOpenHistoryRecord,
    onOpenFollow = onOpenFollow,
    onLoadMoreHistory = onLoadMoreHistory,
    onDeleteHistory = onDeleteHistory,
    onClearHistory = onClearHistory,
    onUpgradeMembership = onUpgradeMembership,
    onRedeemMembershipCard = onRedeemMembershipCard,
    onSignInMembership = onSignInMembership,
    onOpenPointLogs = onOpenPointLogs,
    onProfileEditorChange = onProfileEditorChange,
    onProfileTabChange = onProfileTabChange,
    onSaveProfile = onSaveProfile,
    onAuthModeChange = onAuthModeChange,
    onRegisterEditorChange = onRegisterEditorChange,
    onRefreshRegisterCaptcha = onRefreshRegisterCaptcha,
    onSendRegisterCode = onSendRegisterCode,
    onRegister = onRegister,
    onFindPasswordEditorChange = onFindPasswordEditorChange,
    onSendFindPasswordCode = onSendFindPasswordCode,
    onFindPassword = onFindPassword,
    onOpenSettingsUpdate = onOpenSettingsUpdate,
    onOpenSettingsCache = onOpenSettingsCache,
    onOpenSettingsAgreement = onOpenSettingsAgreement,
    onOpenSettingsLogs = onOpenSettingsLogs,
    onSendEmailCode = onSendEmailCode,
    onBindEmail = onBindEmail,
    onUnbindEmail = onUnbindEmail
)
